### ISSUE TITLE
Question of the memory usage mentioned in the documentation

### ISSUE THREAD

**Issue by phupe** [bioinfo-pf-curie/mpiSORT#22]
It is written in the docs in the section _Informatic resources / Memory_ :

* The total memory used during the sorting is around **one and a half the size of the SAM file**.

* The total memory needed in this case is around **2.5 the individual SAM size**.

I think that if should be 2.5 the size of the SAM size. Is it correct?

**Comment by fredjarlier** [comment]
No. Because in the first part the SAM file contains all chromosomes and each chromosome is sorted successively. In that case the upper bound  memory is the complete sam plus internals structures plus the size of the biggest chromosome.

In the second case each SAM contains only one chromosome this is why we need 2.5 time the total size due to an internal copy.

In general the second method is recommended because the memory upper bound is much less than in the first case.

**Comment by fredjarlier** [comment]
fixed
